### ISSUE TITLE
Error with components/CircularBuffer with submodule update

### ISSUE THREAD

**Issue by Vweston** [An00bIS47/Homekit#6]
git submodule update --init --recursive

fatal: No url found for submodule path 'components/CircularBuffer' in .gitmodules

**Comment by An00bIS47** [comment]
Thanks for reporting this issue. 
I have updated the gitmodules file. Please have a look if it is working for you now.

**Comment by Vweston** [comment]
Thanks, it did fix cloning. Now onto getting a successful compile/link.
I’m getting mbed errors. If I defines to the espconfig.h file as you specify, will it cause problems with other esp project compiles??

Thanks 

-- VW

**Comment by An00bIS47** [comment]
I guess it won't cause any problems with other projects.
i will close this issue because this problem is solved. 

If you encounter any other problems, please open another issue.
Thank you!
